// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHYYSjuWU4iKF0_-Z7eFJJLoSNvNGUDo',
    appId: '1:307370064411:web:1c110fb8418067417356be',
    messagingSenderId: '307370064411',
    projectId: 'flutter-authentication-a-100a0',
    authDomain: 'flutter-authentication-a-100a0.firebaseapp.com',
    storageBucket: 'flutter-authentication-a-100a0.appspot.com',
    measurementId: 'G-VKLMY0V6EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjM0leI_14cvxAzN7gUclfsjXFighz5A',
    appId: '1:307370064411:android:2acdc79b8342d21e7356be',
    messagingSenderId: '307370064411',
    projectId: 'flutter-authentication-a-100a0',
    storageBucket: 'flutter-authentication-a-100a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD553GGTP9VTsYYq1ZxQZeFD5CYGKEHfdE',
    appId: '1:307370064411:ios:130b7cc2a21db2827356be',
    messagingSenderId: '307370064411',
    projectId: 'flutter-authentication-a-100a0',
    storageBucket: 'flutter-authentication-a-100a0.appspot.com',
    iosBundleId: 'com.example.poc2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD553GGTP9VTsYYq1ZxQZeFD5CYGKEHfdE',
    appId: '1:307370064411:ios:130b7cc2a21db2827356be',
    messagingSenderId: '307370064411',
    projectId: 'flutter-authentication-a-100a0',
    storageBucket: 'flutter-authentication-a-100a0.appspot.com',
    iosBundleId: 'com.example.poc2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbHYYSjuWU4iKF0_-Z7eFJJLoSNvNGUDo',
    appId: '1:307370064411:web:03f1f0accda4e8f77356be',
    messagingSenderId: '307370064411',
    projectId: 'flutter-authentication-a-100a0',
    authDomain: 'flutter-authentication-a-100a0.firebaseapp.com',
    storageBucket: 'flutter-authentication-a-100a0.appspot.com',
    measurementId: 'G-CEPS3FH82C',
  );
}
