// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCtCESjoNxuSKzUkj-tQeEBM2hRGv14pGc',
//     appId: '1:775014350651:web:edd5991c1781552420411e',
//     messagingSenderId: '775014350651',
//     projectId: 'e-commerce-app-1e890',
//     authDomain: 'e-commerce-app-1e890.firebaseapp.com',
//     storageBucket: 'e-commerce-app-1e890.appspot.com',
//     measurementId: 'G-FXTLBHLR5W',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAGONfbqIgvPMKl9028Y6vLioNcqHDiuEg',
//     appId: '1:775014350651:android:6daee160f9bcc70f20411e',
//     messagingSenderId: '775014350651',
//     projectId: 'e-commerce-app-1e890',
//     storageBucket: 'e-commerce-app-1e890.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB8GrrQJ0bqp2fnifYxVFlCJXHsU70pqQc',
//     appId: '1:775014350651:ios:d92a01831e2cbc3d20411e',
//     messagingSenderId: '775014350651',
//     projectId: 'e-commerce-app-1e890',
//     storageBucket: 'e-commerce-app-1e890.appspot.com',
//     iosBundleId: 'com.example.eCommerceApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB8GrrQJ0bqp2fnifYxVFlCJXHsU70pqQc',
//     appId: '1:775014350651:ios:d92a01831e2cbc3d20411e',
//     messagingSenderId: '775014350651',
//     projectId: 'e-commerce-app-1e890',
//     storageBucket: 'e-commerce-app-1e890.appspot.com',
//     iosBundleId: 'com.example.eCommerceApp',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCtCESjoNxuSKzUkj-tQeEBM2hRGv14pGc',
//     appId: '1:775014350651:web:c82824182fc3e19820411e',
//     messagingSenderId: '775014350651',
//     projectId: 'e-commerce-app-1e890',
//     authDomain: 'e-commerce-app-1e890.firebaseapp.com',
//     storageBucket: 'e-commerce-app-1e890.appspot.com',
//     measurementId: 'G-BF96VT3QP8',
//   );
// }
